---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: generic/rhel7
    driver:
      provider: hyperv
      network:
        -  ["public_network", {bridge: "Private"}]

suites:
  - name: default
    run_list:
      - recipe[wbc_rhel_base::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      splunk:
        server_list: splunk-odev-azure.australiaeast.cloudapp.azure.com:9997